sentace = input('enter the sentence :')
print('Your sentence is : ')
word1 = input('enter the word to replace : ')
word2 = input('enter the word to replace it with : ')
print(sentace.replace(word1,word2))
